// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsAh5pD4wSL14t0h4OCvVC6aZMSd7Z9UI',
    appId: '1:476512650017:web:ac7123131f9b7702743460',
    messagingSenderId: '476512650017',
    projectId: 'sovchess',
    authDomain: 'sovchess.firebaseapp.com',
    storageBucket: 'sovchess.firebasestorage.app',
    measurementId: 'G-MMHEH1M2E9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjMMDInwiL6w8KvNHfXi2zqOrydU-LZUI',
    appId: '1:476512650017:android:9a9fbe3259bbe1dd743460',
    messagingSenderId: '476512650017',
    projectId: 'sovchess',
    storageBucket: 'sovchess.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5ONsrezJEW3jG12wY1HHzdeYApY1M_U0',
    appId: '1:476512650017:ios:fc053b600cefd1bc743460',
    messagingSenderId: '476512650017',
    projectId: 'sovchess',
    storageBucket: 'sovchess.firebasestorage.app',
    iosBundleId: 'com.example.opensovereignchessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5ONsrezJEW3jG12wY1HHzdeYApY1M_U0',
    appId: '1:476512650017:ios:fc053b600cefd1bc743460',
    messagingSenderId: '476512650017',
    projectId: 'sovchess',
    storageBucket: 'sovchess.firebasestorage.app',
    iosBundleId: 'com.example.opensovereignchessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsAh5pD4wSL14t0h4OCvVC6aZMSd7Z9UI',
    appId: '1:476512650017:web:692edd14c4a61acd743460',
    messagingSenderId: '476512650017',
    projectId: 'sovchess',
    authDomain: 'sovchess.firebaseapp.com',
    storageBucket: 'sovchess.firebasestorage.app',
    measurementId: 'G-9M7SDKXDHD',
  );
}
