name: frogserver
description: Deprecated backend server for opensovereignchess_app
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.8.1"

resolution: workspace

dependencies:
  dart_frog: ^1.1.0

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^5.1.0
